name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "🚀 Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "🧹 Maintenance"
    labels:
      - "chore"
      - "dependencies"
template: |
  ## What's Changed
  $CHANGES

  ## Installation

  ### From Release
  Download the latest release for your platform from the [releases page](https://github.com/pbouamriou/watch-fs/releases).

  ### Using Go
  ```bash
  go install github.com/pbouamriou/watch-fs/cmd/watch-fs@v$RESOLVED_VERSION
  ```

  ## Changelog
  $CHANGES
