version: 2

run:
  timeout: 5m

formatters:
  enable:
    - gofmt
    - goimports

formatters-settings:
  goimports:
    local-prefix: github.com/pbouamriou/watch-fs

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
