#!/bin/bash

# Test script for Mac French keyboards
# Test of alternative navigation keys

echo "🍎 Navigation keys test for MacBook Pro with French keyboard"
echo "============================================================="
echo ""
echo "📋 Available navigation keys:"
echo ""
echo "🔹 Element by element navigation:"
echo "  • Arrows ↑/↓/←/→ (standard)"
echo "  • h/j/k/l (vim-style, alternative for Mac)"
echo ""
echo "🔹 Page navigation:"
echo "  • Page Up/Page Down (standard)"
echo "  • u/d (alternative for Mac)"
echo ""
echo "🔹 Go to beginning/end:"
echo "  • Home/End (standard)"
echo "  • g/G (vim-style, alternative for Mac)"
echo ""
echo "🎯 Full shortcuts for Mac French keyboard:"
echo "  • h/j/k/l : Navigation (left/down/up/right)"
echo "  • u/d : Previous/next page"
echo "  • g/G : Go to beginning/end"
echo "  • f : Toggle files"
echo "  • d : Toggle directories"
echo "  • a : Toggle aggregation"
echo "  • s : Change sorting"
echo "  • q : Quit"
echo ""
echo "🧪 Test instructions:"
echo "  1. Launch the application: ./bin/watch-fs -path ."
echo "  2. Create some files to generate events"
echo "  3. Test the alternative keys:"
echo "     - h/j/k/l for navigation"
echo "     - u/d for pages"
echo "     - g/G for beginning/end"
echo ""
echo "💡 Note: If the arrows do not work, use h/j/k/l"
echo "✅ All alternative keys are now available!" 