#!/bin/bash

echo "🧪 Complete Navigation Test - watch-fs"
echo "======================================"
echo ""
echo "📋 Creating test events..."
for i in {1..15}; do
    echo "test event $i" > "nav_test_$i.txt"
done

echo "✅ 15 files created for navigation testing"
echo ""
echo "🎯 Test to perform:"
echo "1. Launch the application: ./bin/watch-fs -path ."
echo "2. You should see 15 CREATE events"
echo "3. Test all navigation keys:"
echo ""
echo "   Element by element navigation:"
echo "   - ↑/↓ : Line by line movement"
echo "   - h/j/k/l : Vim-style navigation"
echo ""
echo "   Page navigation:"
echo "   - Page Up/Page Down : Page movement (10 lines)"
echo "   - u/d : Alternative page navigation"
echo ""
echo "   Beginning/End navigation:"
echo "   - Home/End : Go to beginning/end"
echo "   - g/G : Alternative beginning/end navigation"
echo ""
echo "   Other keys:"
echo "   - f : Toggle files"
echo "   - d : Toggle directories"
echo "   - a : Toggle aggregation"
echo "   - s : Change sorting"
echo "   - q : Quit"
echo ""
echo "🔍 Points to verify:"
echo "  ✅ Cursor moves one line at a time"
echo "  ✅ Cursor never leaves the list"
echo "  ✅ Home/End and g/G work correctly"
echo "  ✅ Page Up/Page Down work correctly"
echo ""
echo "🎉 Ready to test!" 