name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    outputs:
      release-body: ${{ steps.release_drafter.outputs.body }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: release-drafter/release-drafter@v5
        id: release_drafter
        with:
          publish: false
          name: ${{ github.ref_name }}
          tag: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    needs: update_release_draft
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24

      - name: Build for multiple platforms
        run: |
          # Get version from tag
          VERSION=${GITHUB_REF#refs/tags/}

          # Linux
          GOOS=linux GOARCH=amd64 go build -ldflags="-X main.version=$VERSION" -o dist/watch-fs-linux-amd64 ./cmd/watch-fs
          GOOS=linux GOARCH=arm64 go build -ldflags="-X main.version=$VERSION" -o dist/watch-fs-linux-arm64 ./cmd/watch-fs

          # macOS
          GOOS=darwin GOARCH=amd64 go build -ldflags="-X main.version=$VERSION" -o dist/watch-fs-darwin-amd64 ./cmd/watch-fs
          GOOS=darwin GOARCH=arm64 go build -ldflags="-X main.version=$VERSION" -o dist/watch-fs-darwin-arm64 ./cmd/watch-fs

          # Windows
          GOOS=windows GOARCH=amd64 go build -ldflags="-X main.version=$VERSION" -o dist/watch-fs-windows-amd64.exe ./cmd/watch-fs
          GOOS=windows GOARCH=arm64 go build -ldflags="-X main.version=$VERSION" -o dist/watch-fs-windows-arm64.exe ./cmd/watch-fs

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/watch-fs-linux-amd64
            dist/watch-fs-linux-arm64
            dist/watch-fs-darwin-amd64
            dist/watch-fs-darwin-arm64
            dist/watch-fs-windows-amd64.exe
            dist/watch-fs-windows-arm64.exe
          draft: false
          prerelease: false
          body: ${{ needs.update_release_draft.outputs.release-body }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
